name: Release
on:
    workflow_dispatch:
    push:
        branches:
            - main
            - fix-release-workflow

jobs:
    release:
        name: Release
        runs-on: ubuntu-22.04
        steps:
            ###################################################
            #
            # Prepare
            #
            ###################################################

            - name: (PREPARE) Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: (PREPARE) Checkout Repository
              uses: actions/checkout@v3
              with:
                  lfs: true

            - name: (PREPARE) Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: yarn

            - name: (PREPARE) Install Node Modules
              run: yarn --frozen-lockfile

            - name: (PREPARE) Setup SocketCAN
              run: |
                  sudo apt-get install -y can-utils libnode-dev linux-modules-extra-$(uname -r)
                  sudo modprobe can
                  sudo modprobe can_raw
                  sudo modprobe vcan

            ###################################################
            #
            # Test
            #
            ###################################################

            - name: (TEST) Check Dependencies
              run: yarn dependencies:check

            - name: (TEST) Check ESLint
              run: yarn lint:check

            - name: (TEST) Check Prettier
              run: yarn style:check

            - name: (TEST) Run Tests
              run: sudo timeout 1m sudo yarn test

            - name: (TEST) Upload Tests to Codacy
              uses: codacy/codacy-coverage-reporter-action@v1
              with:
                  project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
                  coverage-reports: coverage/lcov.info
