name: Tests
on:
    workflow_dispatch:
    push:
        branches:
            - main
            - fix-workflow-tests
    pull_request:
        branches:
            - main

jobs:
    tests:
        name: Tests
        runs-on: ubuntu-22.04
        steps:
            ###################################################
            #
            # Prepare
            #
            ###################################################

            - name: (PREPARE) Checkout Repository
              uses: actions/checkout@v3
              with:
                  lfs: true

            - name: (PREPARE) Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: yarn

            - name: (PREPARE) Install Node Modules
              run: yarn --frozen-lockfile

            - name: (PREPARE) vCAN
              run: |
                  sudo apt-get install -y can-utils
                  sudo apt-get install -y libnode-dev
                  sudo apt-get install linux-modules-extra-$(uname -r)
                  
                  sudo modprobe can | true
                  sudo modprobe can_raw | true
                  sudo modprobe vcan | true
                  
                  sudo ip link add vcan0 type vcan
                  sudo ip link set vcan0

            ###################################################
            #
            # Test
            #
            ###################################################
            - name: (TEST) Check Dependencies
              run: yarn dependencies:check

            - name: (TEST) Check ESLint
              run: yarn lint:check

            - name: (TEST) Check Prettier
              run: yarn style:check

            - name: (TEST) Run Tests
              run: yarn test
